[workspace]
authors = ["suchat tangjarukij <suchat.tangjarukij@gmail.com>"]
channels = ["conda-forge"]
name = "aigen"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
char-nlp = { cmd = "KMP_DUPLICATE_LIB_OK=TRUE python src/scratch/char_level_nlp.py" }

[dependencies]
pydantic = ">=2.11.7,<3"
pydantic-settings = ">=2.9.1,<3"
numpy = ">=2.3.0,<3"

[pypi-dependencies]
torch = ">=2.7.1, <3"
pre-commit = ">=3.5.0,<4"
black = ">=23.10.0,<24"
isort = ">=5.12.0,<6"

